### ISSUE TITLE
Update game_manager.js

### ISSUE THREAD

**Issue by AakashRaina** [kingroryg/Big-Oh#12]
Correct the if statement on line 143,(game_manager.js)

**Comment by kingroryg** [comment]
it is unused. doesn't affect my code .

**Comment by AakashRaina** [comment]
How ?

**Comment by kingroryg** [comment]
it is unnecessary piece of code . you dont win bigo when you reach 2048. I have used the innerhtml, which is parsing O(1) as a string and checking whether outputtext[10] is equal to "O(1)" or not. The statement which determines I win or not is totally different in my code.

**Comment by kingroryg** [comment]
you can remove that sttement if you want to . doesnt matter.
